### PR TITLE
Hide spin icons on length and counter

### PR DESCRIPTION
**Pull request by mlcdf**
(fixes lesspass/lesspass#152)

### CODE REVIEW

**Comment by guillaumevincent** [comment]
Hi @mlcdf,
thank you for your pull request. 

For consistency in LessPass component you should use `#options input[type="number"]` instead of `#passwordCounter::-webkit-inner-spin-button`. 

With this you:

 * reduce number of line you write
 * allow you to rename passwordCounter if your domain change, without changing your CSS
 * allow you to add another input number and keep elements consistent

See https://github.com/lesspass/pure/pull/9/commits/b0fc22a0bd9051a9aab657a7cd6a1051629b57d5 for more details

Can you update your pull request?

Thank you

**Comment by mlcdf** [comment]
Sure, I'll update the PR this evening.

**Comment by mlcdf** [comment]
Done! 

Also, regarding this .min.js file, shouldn't we include it in the .gitignore ?

**Comment by guillaumevincent** [comment]
Thank you @mlcdf 
No for simplicity and because I use my own computer for CI, I add min files in the code. But I'll dot it just before publishing a version, not to add useless diff in git.

**Comment by mlcdf** [comment]
It makes sense!

**Pull request merged**
