### PR TITLE
Improve user experience with the web interface on mobile device.

### PR DESCRIPTION
**Pull request by pgrange**
Thanks for the great work.

My 2cents, trying to improve user experience on mobile devices. Hope this does not mess  with other interfaces (I mean other than the frontend module).

Specifying url input type for site avoid smartphone keyboard to propose
capitalization of first letter and may improve completion depending on
used keyboard.
Same goes with specifying email input type for login.

Regards,

### CODE REVIEW

**Comment by guillaumevincent** [comment]
I think `<input id="login" name="login" type="email">` raise an error if my login is not an email. no ?

I will test it, thanks

**Comment by pgrange** [comment]
Hi, 

It did not raise any issue during my test. 

Regards,

**Comment by guillaumevincent** [comment]
image

I will look at the :invalid css classe to see if I can fix this on firefox

https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid

**Comment by guillaumevincent** [comment]
@pgrange I don't know why your Android browser don't understand `autocapitalize="off"`
I will look at this one soon.

**Comment by guillaumevincent** [comment]
Will try ` autocapitalize="none"` to see if autocapitalize is fixed on android mobile.
see https://github.com/lesspass/pure/commit/d5c41f43b6d0b9d66c520973a28d1d621f3f2e1b

For now I close this one, because input site is not always an url and input login is not always an email. It breaks form validation on some browsers

**Pull request closed without merging**
